#!/usr/bin/env bash

time=$( date +%H:%M )

echo -n "${time} // "

case $( date +%u ) in
	1) echo -n "Seg";;
	2) echo -n "Ter";;
	3) echo -n "Qua";;
	4) echo -n "Qui";;
	5) echo -n "Sex";;
	6) echo -n "Sáb";;
	7) echo -n "Dom";;
esac

day_of_month=$( date +%d  )
month_short=$( date +%b )

echo -n ", ${day_of_month} ${month_short} "
